version: 0.0
os: linux
files:
  - source: /public/index.html
    destination: /
hooks:
  BeforeInstall:
    - location: scripts/install
      timeout: 300
      runas: root
    - location: scripts/start
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop
      timeout: 300
      runas: root

