version: 0.2

phases:
  pre_build:
    commands:
      - echo 'Pre Build Phase ...'
      - curl -sL https://rpm.nodesource.com/setup_17.x | bash -
      - yum -y install nodejs npm --skip-broken
      - npm install --global yarn
      - yarn install
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date` and started Apache server
artifacts:
  files:
    - "**/*"