version: 0.2

phases:
  pre_build:
    commands:
      - echo 'Pre Build Phase ...'
      - curl -sL https://rpm.nodesource.com/setup_17.x | bash -
      - yum -y install nodejs npm --skip-broken
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date` and started Apache server
       # copy the contents of /build to S3
      #- aws s3 cp --recursive --acl public-read ./build s3://awscodepipeline-s3-bucket/ 
      # set the cache-control headers for service-worker.js to prevent
      # browser caching
      #- >
       # aws s3 cp --acl public-read 
        #--cache-control="max-age=0, no-cache, no-store, must-revalidate" 
        #./build/service-worker.js s3://awscodepipeline-s3-bucket/
      # set the cache-control headers for index.html to prevent
      # browser caching
      #- >
       # aws s3 cp --acl public-read 
        #--cache-control="max-age=0, no-cache, no-store, must-revalidate" 
        #./build/index.html s3://awscodepipeline-s3-bucket/
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory : build