version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user

hooks:
  BeforeInstall: 
    - location: scripts/beforeinstall.sh
      timeout: 100
  AfterInstall: 
    - location: scripts/afterinstall.sh
      timeout: 100
  ApplicationStart:
    - location: scripts/onstart.sh
      timeout: 100
    