version: 0.0
os: linux
files:
  - source: /
    destination: /home/app
hooks:
  AfterInstall:
    - location: /scripts/afterinstall.sh
      timeout: 100
  ApplicationStart:
    - location: /scripts/applicationstart.sh
      timeout: 100
