version: 0.0

phases:
  pre_build:
    commands:
      - echo 'Pre Build Phase ...'
      - curl -sL https://rpm.nodesource.com/setup_17.x | bash -
      - yum -y install nodejs npm --skip-broken
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date` and started Apache server
       
      #- aws s3 cp --recursive --acl public-read-write ./build s3://awscodepipeline-s3-bucket/ 
      
artifacts:
  type: zip
  files:
    - "**/*"
  discard-paths: no
  base-directory : build